name: My First CI
on:
    push:
        branches:
            -main

    workflow_dispatch:
        
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Java
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'temurin'

          - name: Check Java version
            run: java --version

          - name: Run Maven test
            run: mvn test
          - name: say hello world
            run: echo "hello world first"

          - name: step2
            run: echo "hi this step two "

          - name: Show current directory
            run: pwd

          - name: List files
            run: ls -la

          - name: Check operating system
            run: uname -a