name: My First CI
on:
    push:
        branches:
            -main

    workflow_dispatch:
        
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:    
          - name: say hello world
            run: echo "hello world first"

          - name: step2
            run: echo "hi this step two "
            
          - name: Show current directory
            run: pwd
          
